import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export async function getServerSideProps() {
  console.log("server");
  return {
    props: { time: new Date().toISOString() },
  };
}

interface HomProps {
  time: string;
}

const Home: NextPage<HomProps> = ({ time }) => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">{time}</h1>
        <h1>
          <Link href="/data/csr">
            <a>CSR</a>
          </Link>
        </h1>
        <h1>
          <Link href="/data/ssg">
            <a>SSG</a>
          </Link>
        </h1>
        <h1>
          <Link href="/data/isr">
            <a>ISR</a>
          </Link>
        </h1>
      </main>
    </div>
  );
};

export default Home;
